import { Profile, Project, Task, Notification, DashboardStats } from '@/types'

export const mockUser: Profile = {
  id: 'user-1',
  full_name: 'Alex Rivera',
  email: 'alex@taskflow.io',
  role: 'admin',
  created_at: new Date().toISOString(),
}

export const mockMembers: Profile[] = [
  { id: 'user-1', full_name: 'Alex Rivera', email: 'alex@taskflow.io', role: 'admin', created_at: '2024-01-01T00:00:00Z' },
  { id: 'user-2', full_name: 'Sam Chen', email: 'sam@taskflow.io', role: 'member', created_at: '2024-01-02T00:00:00Z' },
  { id: 'user-3', full_name: 'Jordan Kim', email: 'jordan@taskflow.io', role: 'member', created_at: '2024-01-03T00:00:00Z' },
  { id: 'user-4', full_name: 'Maya Patel', email: 'maya@taskflow.io', role: 'member', created_at: '2024-01-04T00:00:00Z' },
]

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Redesign Landing Page',
    description: 'Complete overhaul of the marketing website with new brand identity',
    status: 'active',
    owner_id: 'user-1',
    deadline: '2025-06-30',
    created_at: '2024-01-01T00:00:00Z',
    task_count: 12,
    completed_count: 7,
  },
  {
    id: 'proj-2',
    name: 'Mobile App v2.0',
    description: 'Cross-platform React Native app with offline support and push notifications',
    status: 'active',
    owner_id: 'user-1',
    deadline: '2025-07-15',
    created_at: '2024-01-05T00:00:00Z',
    task_count: 24,
    completed_count: 9,
  },
  {
    id: 'proj-3',
    name: 'API Gateway Migration',
    description: 'Move from REST to GraphQL with full type safety and performance improvements',
    status: 'on_hold',
    owner_id: 'user-2',
    deadline: '2025-08-01',
    created_at: '2024-01-10T00:00:00Z',
    task_count: 8,
    completed_count: 3,
  },
  {
    id: 'proj-4',
    name: 'Analytics Dashboard',
    description: 'Real-time analytics platform with custom reporting and data exports',
    status: 'completed',
    owner_id: 'user-1',
    deadline: '2025-04-01',
    created_at: '2023-12-01T00:00:00Z',
    task_count: 16,
    completed_count: 16,
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Design new hero section mockups',
    description: 'Create 3 variations of the hero section with new brand guidelines applied. Include mobile and desktop versions.',
    status: 'in_progress',
    priority: 'high',
    project_id: 'proj-1',
    assigned_to: 'user-3',
    due_date: '2025-05-20',
    created_by: 'user-1',
    created_at: '2024-01-15T00:00:00Z',
    assignee: mockMembers[2],
  },
  {
    id: 'task-2',
    title: 'Implement authentication flow',
    description: 'Build email OTP login with Supabase Auth. Add persistent sessions and protected routes.',
    status: 'done',
    priority: 'critical',
    project_id: 'proj-2',
    assigned_to: 'user-2',
    due_date: '2025-05-10',
    created_by: 'user-1',
    created_at: '2024-01-16T00:00:00Z',
    assignee: mockMembers[1],
  },
  {
    id: 'task-3',
    title: 'Set up GraphQL schema',
    description: 'Define the core data model in GraphQL with proper resolvers and type definitions.',
    status: 'todo',
    priority: 'high',
    project_id: 'proj-3',
    assigned_to: 'user-4',
    due_date: '2025-06-01',
    created_by: 'user-1',
    created_at: '2024-01-18T00:00:00Z',
    assignee: mockMembers[3],
  },
  {
    id: 'task-4',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with request/response examples and error codes.',
    status: 'review',
    priority: 'medium',
    project_id: 'proj-1',
    assigned_to: 'user-2',
    due_date: '2025-05-25',
    created_by: 'user-1',
    created_at: '2024-01-19T00:00:00Z',
    assignee: mockMembers[1],
  },
  {
    id: 'task-5',
    title: 'Performance audit and optimization',
    description: 'Run Lighthouse audits and fix all performance issues to achieve 90+ score.',
    status: 'todo',
    priority: 'medium',
    project_id: 'proj-2',
    assigned_to: 'user-3',
    due_date: '2025-07-01',
    created_by: 'user-1',
    created_at: '2024-01-20T00:00:00Z',
    assignee: mockMembers[2],
  },
  {
    id: 'task-6',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment to staging and production.',
    status: 'in_progress',
    priority: 'high',
    project_id: 'proj-2',
    assigned_to: 'user-1',
    due_date: '2025-05-15',
    created_by: 'user-1',
    created_at: '2024-01-21T00:00:00Z',
    assignee: mockMembers[0],
  },
  {
    id: 'task-7',
    title: 'Create onboarding flow',
    description: 'Build a multi-step onboarding experience for new users with progress tracking.',
    status: 'todo',
    priority: 'low',
    project_id: 'proj-1',
    assigned_to: 'user-4',
    due_date: '2025-06-15',
    created_by: 'user-1',
    created_at: '2024-01-22T00:00:00Z',
    assignee: mockMembers[3],
  },
  {
    id: 'task-8',
    title: 'Database schema migration',
    description: 'Run migration scripts for v2 schema changes with backward compatibility.',
    status: 'done',
    priority: 'critical',
    project_id: 'proj-2',
    assigned_to: 'user-2',
    due_date: '2025-04-30',
    created_by: 'user-1',
    created_at: '2024-01-23T00:00:00Z',
    assignee: mockMembers[1],
  },
]

export const mockNotifications: Notification[] = [
  { id: 'n-1', user_id: 'user-1', title: 'Task Updated', message: 'Sam Chen updated "Implement authentication flow" to Done', is_read: false, created_at: new Date(Date.now() - 1800000).toISOString() },
  { id: 'n-2', user_id: 'user-1', title: 'New Comment', message: 'Jordan Kim commented on "Design new hero section"', is_read: false, created_at: new Date(Date.now() - 3600000).toISOString() },
  { id: 'n-3', user_id: 'user-1', title: 'Task Assigned', message: 'You were assigned to "Setup CI/CD pipeline"', is_read: true, created_at: new Date(Date.now() - 86400000).toISOString() },
  { id: 'n-4', user_id: 'user-1', title: 'Project Updated', message: 'API Gateway Migration moved to On Hold', is_read: true, created_at: new Date(Date.now() - 172800000).toISOString() },
]

export const mockStats: DashboardStats = {
  totalTasks: 8,
  completedTasks: 2,
  pendingTasks: 4,
  overdueTasks: 1,
  totalProjects: 4,
  activeProjects: 2,
  teamMembers: 4,
}

export const mockChartData = [
  { name: 'Mon', completed: 4, created: 6 },
  { name: 'Tue', completed: 7, created: 5 },
  { name: 'Wed', completed: 3, created: 8 },
  { name: 'Thu', completed: 9, created: 7 },
  { name: 'Fri', completed: 6, created: 4 },
  { name: 'Sat', completed: 2, created: 3 },
  { name: 'Sun', completed: 5, created: 6 },
]
